// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLY_g-efxqUgFQPFjs5SYv9j65br85IvE',
    appId: '1:142473796180:web:8992dcc6863cef2a336bc1',
    messagingSenderId: '142473796180',
    projectId: 'parkcle-5ccd4',
    authDomain: 'parkcle-5ccd4.firebaseapp.com',
    storageBucket: 'parkcle-5ccd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0UKTnf6-CsrGX5QXPM6o0zvjj2gUkEVc',
    appId: '1:142473796180:android:68c04d9390ebd19c336bc1',
    messagingSenderId: '142473796180',
    projectId: 'parkcle-5ccd4',
    storageBucket: 'parkcle-5ccd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUCtT-raZS7OXQ8E0_2B38TX2dkrHjqII',
    appId: '1:142473796180:ios:4a71b83e6ddc6ffe336bc1',
    messagingSenderId: '142473796180',
    projectId: 'parkcle-5ccd4',
    storageBucket: 'parkcle-5ccd4.firebasestorage.app',
    iosBundleId: 'com.example.parkcle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUCtT-raZS7OXQ8E0_2B38TX2dkrHjqII',
    appId: '1:142473796180:ios:4a71b83e6ddc6ffe336bc1',
    messagingSenderId: '142473796180',
    projectId: 'parkcle-5ccd4',
    storageBucket: 'parkcle-5ccd4.firebasestorage.app',
    iosBundleId: 'com.example.parkcle',
  );
}
